# Generated by Django 4.2 on 2023-04-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Blog Image: ')),
                ('title', models.CharField(max_length=255, verbose_name='Blog Title: ')),
                ('txt', models.TextField(verbose_name='Blog Text: ')),
                ('date', models.DateField(verbose_name='Blog adding time: ')),
            ],
            options={
                'verbose_name': 'Introduction',
                'verbose_name_plural': 'Introductions',
            },
        ),
    ]
