# Generated by Django 4.2 on 2023-04-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_singleservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Image ')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('name', models.CharField(max_length=50, verbose_name='Name ')),
            ],
            options={
                'verbose_name': 'OurGallery',
                'verbose_name_plural': 'OurGalleries',
            },
        ),
    ]
