# Generated by Django 4.2 on 2023-04-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ourgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourgallery',
            name='img_tn',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Image '),
        ),
    ]
