# Generated by Django 4.2 on 2023-04-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Services Title: ')),
                ('txt1', models.TextField(verbose_name='First Text: ')),
                ('txt2', models.TextField(verbose_name='Second Text: ')),
            ],
            options={
                'verbose_name': 'OurService',
                'verbose_name_plural': 'OurServices',
            },
        ),
    ]
