# Generated by Django 4.2 on 2023-04-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ourservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_link', models.CharField(max_length=255, verbose_name='Icon name ')),
                ('txt', models.TextField(verbose_name='Text ')),
            ],
            options={
                'verbose_name': 'SingleService',
                'verbose_name_plural': 'SingleService',
            },
        ),
    ]
