# Generated by Django 4.2 on 2023-04-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ourgallery_img_tn'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('txt1', models.TextField(verbose_name='First Text: ')),
                ('txt2', models.TextField(verbose_name='Second Text: ')),
                ('txt3', models.TextField(verbose_name='Third Text: ')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
    ]
